const $=id=>document.getElementById(id);let data={};let charts={};
async function api(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});let j={};try{j=await r.json()}catch{}if(!r.ok)throw Error(j.error||'Request failed');return j}
function msg(t,type='success'){ $('toast').innerHTML=`<div class="alert alert-${type} py-2">${t}</div>`;setTimeout(()=>$('toast').innerHTML='',3500)}
async function login(){try{const j=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:$('email').value,password:$('password').value})});start(j.user)}catch(e){$('authMsg').innerHTML=`<div class="alert alert-danger">${e.message}</div>`}}
async function register(){try{const j=await api('/api/auth/register',{method:'POST',body:JSON.stringify({name:$('regName').value,email:$('regEmail').value,password:$('regPassword').value,confirmPassword:$('regConfirm').value})});start(j.user)}catch(e){$('authMsg').innerHTML=`<div class="alert alert-danger">${e.message}</div>`}}
async function logout(){await api('/api/auth/logout',{method:'POST'});location.reload()}
async function start(user){$('loginView').classList.add('d-none');$('appView').classList.remove('d-none');$('welcome').textContent=`Welcome, ${user.name}`;buildNav();await loadAll();show('dashboard')}
function buildNav(){const items=[['dashboard','Dashboard'],['subjects','Subjects'],['topics','Topics'],['assignments','Assignments'],['exams','Exams'],['availability','Study Time'],['planner','Study Planner'],['calendar','Calendar'],['progress','Progress'],['ai','AI Study Plan'],['reports','Reports'],['profile','Profile']];$('nav').innerHTML=items.map(x=>`<a href="#" data-page="${x[0]}" onclick="show('${x[0]}');return false">${x[1]}</a>`).join('')}
async function loadAll(){const [d,s,t,a,e,ss,av,p]=await Promise.all([api('/api/dashboard'),api('/api/subjects'),api('/api/topics'),api('/api/assignments'),api('/api/exams'),api('/api/study-sessions'),api('/api/availability'),api('/api/progress')]);data={dash:d,subjects:s,topics:t,assignments:a,exams:e,sessions:ss,availability:av,progress:p};renderAll()}
function show(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('#nav a').forEach(x=>x.classList.toggle('active',x.dataset.page===id));$('pageTitle').textContent=id==='ai'?'AI Study Plan':id[0].toUpperCase()+id.slice(1);if(id==='calendar')setTimeout(renderCalendar,50)}
function subjectName(id){return data.subjects.find(s=>String(s._id)===String(id))?.name||'—'}
function renderAll(){renderDashboard();renderSubjects();renderTopics();renderAssignments();renderExams();renderAvailability();renderPlanner();renderProgress();renderAI();renderReports();renderProfile()}
function renderDashboard(){const d=data.dash,s=data.subjects.map(x=>`<div class="col-md-6 mb-3"><div class="card p-3"><div class="d-flex justify-content-between"><b>${x.name}</b><span>${Math.round(data.progress.subject.find(y=>y.name===x.name)?.progress||0)}%</span></div><div class="progress mt-2"><div class="progress-bar" style="width:${data.progress.subject.find(y=>y.name===x.name)?.progress||0}%"></div></div></div></div>`).join('');$('dashboard').innerHTML=`<div class="row g-3">${[['Overall',d.stats.overall+'%'],['Subjects',d.stats.subjects],['Pending topics',d.stats.pendingTopics],['Completed topics',d.stats.completedTopics],['Upcoming exams',d.stats.upcomingExams],['Pending assignments',d.stats.pendingAssignments],['Today',Math.round(d.stats.todayMinutes/60*10)/10+' h'],['Week',Math.round(d.stats.weeklyMinutes/60*10)/10+' h']].map(x=>`<div class="col-6 col-md-3"><div class="card p-3"><div class="small-muted">${x[0]}</div><div class="stat">${x[1]}</div></div></div>`).join('')}</div><div class="row mt-3"><div class="col-lg-8"><div class="card p-3"><h5>Subject progress</h5><div class="row">${s}</div></div></div><div class="col-lg-4"><div class="card p-3"><h5>Smart alert</h5><p>${d.weak?`<b>${d.weak.subject.name}</b> is your weakest subject at ${d.weak.progress}%.`:'Add subjects and topics to get recommendations.'}</p><p class="small-muted">${d.weak?'Recommended: give this subject extra time without exceeding your availability.':''}</p></div></div></div>`}
function renderSubjects(){ $('subjects').innerHTML=`<div class="card p-3 mb-3"><h5>Add subject</h5><form onsubmit="addSubject(event)" class="row g-2"><input name="name" class="form-control col" placeholder="Subject name" required><input name="code" class="form-control col" placeholder="Code"><select name="difficulty" class="form-select col"><option>Easy</option><option selected>Medium</option><option>Hard</option></select><input name="color" type="color" value="#6366f1" class="form-control form-control-color"><button class="btn btn-primary col-auto">Add</button></form></div><div class="card p-3"><h5>Your subjects</h5><div class="table-responsive"><table class="table"><thead><tr><th>Name</th><th>Code</th><th>Difficulty</th><th>Progress</th><th></th></tr></thead><tbody>${data.subjects.map(s=>`<tr><td><span style="display:inline-block;width:10px;height:10px;background:${s.color};border-radius:50%"></span> ${s.name}</td><td>${s.code||''}</td><td>${s.difficulty}</td><td>${data.progress.subject.find(x=>x.name===s.name)?.progress||0}%</td><td><button class="btn btn-sm btn-outline-danger" onclick="del('/api/subjects/${s._id}')">Delete</button></td></tr>`).join('')}</tbody></table></div></div>`}
function renderTopics(){ $('topics').innerHTML=`<div class="card p-3 mb-3"><h5>Add topic</h5><form onsubmit="addTopic(event)" class="row g-2"><select name="subjectId" class="form-select col" required>${data.subjects.map(s=>`<option value="${s._id}">${s.name}</option>`).join('')}</select><input name="name" class="form-control col" placeholder="Topic" required><select name="difficulty" class="form-select col"><option>Easy</option><option selected>Medium</option><option>Hard</option></select><input name="estimatedMinutes" type="number" min="15" value="60" class="form-control col" placeholder="Minutes"><select name="priority" class="form-select col"><option>Low</option><option selected>Medium</option><option>High</option></select><button class="btn btn-primary col-auto">Add</button></form></div><div class="card p-3"><h5>Topics</h5><div class="table-responsive"><table class="table"><thead><tr><th>Topic</th><th>Subject</th><th>Difficulty</th><th>Progress</th><th>Status</th><th></th></tr></thead><tbody>${data.topics.map(t=>`<tr><td>${t.name}</td><td>${subjectName(t.subjectId)}</td><td>${t.difficulty}</td><td><input type="range" min="0" max="100" value="${t.progress}" onchange="updateTopic('${t._id}',{progress:+this.value,status:this.value==100?'Completed':'In Progress'})"><span>${t.progress}%</span></td><td>${t.status}</td><td><button class="btn btn-sm btn-success" onclick="completeTopic('${t._id}')">✓</button> <button class="btn btn-sm btn-outline-danger" onclick="del('/api/topics/${t._id}')">Delete</button></td></tr>`).join('')}</tbody></table></div></div>`}
function renderAssignments(){ $('assignments').innerHTML=`<div class="card p-3 mb-3"><h5>Add assignment</h5><form onsubmit="addAssignment(event)" class="row g-2"><input name="title" class="form-control col" placeholder="Title" required><select name="subjectId" class="form-select col">${data.subjects.map(s=>`<option value="${s._id}">${s.name}</option>`).join('')}</select><input name="deadline" type="datetime-local" class="form-control col" required><input name="estimatedMinutes" type="number" value="60" class="form-control col"><select name="priority" class="form-select col"><option>Low</option><option selected>Medium</option><option>High</option></select><button class="btn btn-primary col-auto">Add</button></form></div><div class="card p-3"><h5>Assignments</h5>${data.assignments.map(a=>`<div class="d-flex justify-content-between border-bottom py-2"><div><b>${a.title}</b> · ${subjectName(a.subjectId)}<br><span class="small-muted">Due ${new Date(a.deadline).toLocaleString()} · ${a.priority}</span></div><div><span class="badge ${new Date(a.deadline)<new Date()&&a.status!=='Completed'?'text-bg-danger':'text-bg-secondary'}">${a.status}</span> <button class="btn btn-sm btn-outline-danger" onclick="del('/api/assignments/${a._id}')">×</button></div></div>`).join('')}</div>`}
function renderExams(){ $('exams').innerHTML=`<div class="card p-3 mb-3"><h5>Add exam</h5><form onsubmit="addExam(event)" class="row g-2"><input name="name" class="form-control col" placeholder="Exam name" required><select name="subjectId" class="form-select col">${data.subjects.map(s=>`<option value="${s._id}">${s.name}</option>`).join('')}</select><input name="date" type="datetime-local" class="form-control col" required><select name="importance" class="form-select col"><option>Low</option><option selected>Medium</option><option>High</option></select><button class="btn btn-primary col-auto">Add</button></form></div><div class="card p-3"><h5>Upcoming exams</h5>${data.exams.sort((a,b)=>new Date(a.date)-new Date(b.date)).map(e=>{let days=Math.ceil((new Date(e.date)-new Date())/86400000);return `<div class="border-bottom py-2"><b>${e.name}</b> · ${subjectName(e.subjectId)} · ${new Date(e.date).toLocaleString()} <span class="badge ${days<=3?'text-bg-danger':'badge-soft'}">${days} day(s)</span></div>`}).join('')}</div>`}
function renderAvailability(){const days=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];$('availability').innerHTML=`<div class="card p-3"><h5>Available study time</h5><p class="small-muted">Add time windows. The scheduler never places sessions outside these windows.</p>${days.map((d,i)=>`<form onsubmit="addAvail(event,${i})" class="row g-2 mb-2"><div class="col-md-3 pt-2"><b>${d}</b></div><input name="start" type="time" class="form-control col" value="18:00"><input name="end" type="time" class="form-control col" value="20:00"><button class="btn btn-outline-primary col-auto">Add</button></form><div>${data.availability.filter(a=>a.day===i).map(a=>`<span class="badge text-bg-light me-1 mb-1">${a.start}–${a.end} <button class="btn-close" style="font-size:8px" onclick="del('/api/availability/${a._id}')"></button></span>`).join('')}</div>`).join('')}</div>`}
function renderPlanner(){ $('planner').innerHTML=`<div class="card p-3"><h5>Personalized schedule</h5><p>The scheduler ranks urgent exams, deadlines, difficulty, low progress and priorities, then fills only your available windows without overlaps.</p><button class="btn btn-primary mb-3" onclick="generatePlan()">Generate 14-day schedule</button>${data.sessions.sort((a,b)=>new Date(a.date)-new Date(b.date)).map(s=>`<div class="border rounded p-2 mb-2 d-flex justify-content-between"><div><b>${s.title}</b> · ${subjectName(s.subjectId)}<br><span class="small-muted">${new Date(s.date).toLocaleDateString()} · ${s.startTime}–${s.endTime} · ${s.type}</span></div><div><span class="badge text-bg-${s.priority==='High'?'danger':s.priority==='Medium'?'warning':'secondary'}">${s.priority}</span> <select onchange="sessionStatus('${s._id}',this.value)" class="form-select form-select-sm d-inline-block" style="width:auto"><option ${s.status==='Pending'?'selected':''}>Pending</option><option ${s.status==='In Progress'?'selected':''}>In Progress</option><option ${s.status==='Completed'?'selected':''}>Completed</option><option ${s.status==='Missed'?'selected':''}>Missed</option><option ${s.status==='Skipped'?'selected':''}>Skipped</option></select></div></div>`).join('')}</div>`}
function renderCalendar(){const el=$('calendar');if(!el.classList.contains('active'))return;el.innerHTML='<div class="card p-3"><div id="fc"></div></div>';const c=new FullCalendar.Calendar(document.getElementById('fc'),{initialView:'dayGridMonth',height:'auto',events:data.sessions.map(s=>({title:`${s.title} · ${s.startTime}`,start:new Date(s.date).toISOString().slice(0,10),extendedProps:s})),eventClick:i=>alert(`${i.event.title}\nStatus: ${i.event.extendedProps.status}\nPriority: ${i.event.extendedProps.priority}`)});c.render()}
function renderProgress(){const p=data.progress;$('progress').innerHTML=`<div class="row g-3"><div class="col-lg-7"><div class="card p-3"><h5>Subject progress</h5><canvas id="subjectChart"></canvas></div></div><div class="col-lg-5"><div class="card p-3"><h5>Difficulty distribution</h5><canvas id="diffChart"></canvas></div></div></div>`;setTimeout(()=>{charts.subject?.destroy();charts.diff?.destroy();charts.subject=new Chart($('subjectChart'),{type:'bar',data:{labels:p.subject.map(x=>x.name),datasets:[{label:'Progress %',data:p.subject.map(x=>x.progress)}]}});charts.diff=new Chart($('diffChart'),{type:'doughnut',data:{labels:Object.keys(p.difficulty),datasets:[{data:Object.values(p.difficulty)}]}})},30)}
function renderAI(){$('ai').innerHTML=`<div class="card p-4"><h5>🤖 AI Study Plan</h5><p class="small-muted">Uses an optional AI endpoint when configured. Otherwise the built-in rule-based planner works offline.</p><input id="aiExam" type="date" class="form-control mb-2"><input id="aiHours" type="number" step="0.5" value="2" class="form-control mb-2" placeholder="Daily hours"><button class="btn btn-primary" onclick="aiPlan()">Generate plan</button><pre id="aiOut" class="mt-3 p-3 bg-light rounded"></pre></div>`}
function renderReports(){$('reports').innerHTML=`<div class="card p-4"><h5>Weekly report</h5><button class="btn btn-outline-primary" onclick="weekly()">Refresh report</button><div id="weeklyOut" class="mt-3"></div></div>`}
function renderProfile(){$('profile').innerHTML=`<div class="card p-4"><h5>Profile</h5><p>${$('welcome').textContent}</p><p class="small-muted">Session length and break preferences are stored with your account. The core demo keeps the UI simple for a college project.</p></div>`}
async function addSubject(e){e.preventDefault();const f=new FormData(e.target);await api('/api/subjects',{method:'POST',body:JSON.stringify(Object.fromEntries(f))});await loadAll();msg('Subject added')}
async function addTopic(e){e.preventDefault();const f=new FormData(e.target);await api('/api/topics',{method:'POST',body:JSON.stringify(Object.fromEntries(f))});await loadAll();msg('Topic added')}
async function addAssignment(e){e.preventDefault();const f=new FormData(e.target);await api('/api/assignments',{method:'POST',body:JSON.stringify(Object.fromEntries(f))});await loadAll();msg('Assignment added')}
async function addExam(e){e.preventDefault();const f=new FormData(e.target);await api('/api/exams',{method:'POST',body:JSON.stringify(Object.fromEntries(f))});await loadAll();msg('Exam added')}
async function addAvail(e,day){e.preventDefault();const f=new FormData(e.target);await api('/api/availability',{method:'POST',body:JSON.stringify({day,start:f.get('start'),end:f.get('end')})});await loadAll();msg('Availability added')}
async function del(url){if(!confirm('Delete this item?'))return;await api(url,{method:'DELETE'});await loadAll();msg('Deleted')}
async function updateTopic(id,body){await api('/api/topics/'+id,{method:'PUT',body:JSON.stringify(body)});await loadAll();msg('Progress updated')}
async function completeTopic(id){await updateTopic(id,{progress:100,status:'Completed'})}
async function sessionStatus(id,status){await api('/api/planner/reschedule',{method:'POST',body:JSON.stringify({sessionId:id,status})});await loadAll();msg(status==='Missed'?'Your schedule has been updated because you missed a task.':'Schedule updated')}
async function generatePlan(){try{const j=await api('/api/planner/generate',{method:'POST',body:JSON.stringify({days:14})});await loadAll();show('planner');msg(j.message)}catch(e){msg(e.message,'danger')}}
async function aiPlan(){const subjects=data.progress.subject.map(s=>({name:s.name,progress:s.progress}));const j=await api('/api/ai/study-plan',{method:'POST',body:JSON.stringify({examDate:$('aiExam').value,availableHours:$('aiHours').value,subjects})});$('aiOut').textContent=`Source: ${j.source}\n\n${j.plan}`}
async function weekly(){const w=await api('/api/progress/weekly');$('weeklyOut').innerHTML=`<h4>${Math.round(w.completed/60*10)/10} completed hours / ${Math.round(w.planned/60*10)/10} planned</h4><p>Missed tasks: ${w.missed}</p><p>Strongest: ${w.strongest?.name||'—'} (${w.strongest?.progress||0}%)</p><p>Weakest: ${w.weakest?.name||'—'} (${w.weakest?.progress||0}%)</p><p>Recommendation: spend extra time on the weakest subject while staying inside availability.</p>`}
(async()=>{try{const j=await api('/api/auth/me');start(j.user)}catch{}})();
